- name: setup Earlang Repo
  ansible.builtin.shell:
    name: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh |  bash

- name: set up Rabbitmq Repo
ansible.builtin.shell:
  name: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install Rabbit and Earlang
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - erlang
    state: installed

- name: Start Rabbitmq Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Add application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present